
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author harsh
 */
public class signup extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String user;
    String ran1;
    int ran2;

    /**
     * Creates new form signup
     */
    public signup(String ss,String ran,int ran2) {
        initComponents();
        this.user=ss;
        jLabel3.setText(user);
        this.ran1=ran;
        this.ran2=ran2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LogInPassword");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel4.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String dbURL = "jdbc:mysql://localhost:3306/java";
       String username = "root";
       String password = "";
 
     try {
 String userid=jLabel3.getText();
 Connection conn = DriverManager.getConnection(dbURL, username, password);
 String sql = "SELECT * FROM newusers where user_id='"+userid+"'";
 
 
Statement statement = conn.createStatement();
ResultSet result = statement.executeQuery(sql);
int count = 0;
while (result.next()){
    String user = result.getString("user_id");
    String pass = result.getString("password");
     
           String en=pass,dec="";
       String decry;
       String dec2,dec4;
       String aa,mainstr;
       mainstr="";
       String main;
       main="";
       int cou;
       int cou2;
       int ssaa=0;
       int ssssaa;
       String ssss;
       ssss="";
       cou2=0;
       String ss;
       ss="";
       ss=ss+en.charAt((int)(en.length()-1));
       dec2="";
       dec4="";
       int n;
       int aaaa[];
       int ssssaaaa[];
       n=0;
       String option[]= {"$","1","2","3","4","5","6","7","8","9","0","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","@","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","#","*","!","%","^","&","(",")","_","-","+","=","~","?","/","[","]","{","}","|","`",":",";",",",".","<"};
       int numb=(int)en.length();
       String sp="";sp=sp+en.charAt(numb-1);
       int spv=0;
       for(int ke=0;;ke++)
       {
        ssss="";
        ssss=ssss+option[ke];
           if((sp.charAt(0))==ssss.charAt(0))
           {
               break;
           }
           spv++;
       }
       spv=spv-10;
       System.out.println(spv);
       for(int i=0;i<(int)en.length()-2;i++)
       {
           dec=dec+en.charAt(i);
       }
       System.out.println(dec);
       dec2=dec;
       int inc;
       inc=0;
       if(spv==2)
       {
       for(int i=0;i<25;i++)
       {
        if((int)dec.length()==8+(i*(6)))
        {
            n=2+i;
            break;
        }
       }
    }

       if(spv==3)
       {
       for(int i=0;i<25;i++)
       {
        if((int)dec.length()==10+(i*(8)))
        {
            n=2+i;
            break;
        }
       }
    }
    if(spv==4)
       {
       for(int i=0;i<25;i++)
       {
        if((int)dec.length()==12+(i*(10)))
        {
            n=2+i;
            break;
        }
       }
    }
      /* if((int)dec.length()==10)
       {
           n=2;
       }
       if((int)dec.length()==18)
       {
           n=3;
       }
       if((int)dec.length()==26)
       {
           n=4;
       }
       if((int)dec.length()==34)
       {
           n=5;
       }
       if((int)dec.length()==42)
       {
           n=6;
       }
       if((int)dec.length()==50)
       {
           n=7;
       }
       if((int)dec.length()==58)
       {
           n=8;
       }
       if((int)dec.length()==66)
       {
           n=9;
       }if((int)dec.length()==74)
       {
           n=10;
       }
       if((int)dec.length()==82)
       {
           n=11;
       }
       if((int)dec.length()==90)
       {
           n=12;
       }
       if((int)dec.length()==98)
       {
           n=13;
       }
       if((int)dec.length()==106)
       {
           n=14;
       }
       if((int)dec.length()==114)
       {
           n=15;
       }
       if((int)dec.length()==122)
       {
           n=16;
       }
       if((int)dec.length()==130)
       {
           n=17;
       }
       if((int)dec.length()==138)
       {
           n=18;
       }*/
       System.out.println(n);
       for(int i=0;i<n;i++)
       {
       for(int j=inc;j<inc+2;j++)
       {
           dec4=dec4+dec.charAt(j);
       }
       inc=inc+((spv*2)+2);
    }
       System.out.println(dec4);
       System.out.println(ss.charAt(0));
       aaaa=new int[(int)dec4.length()];
       ssssaaaa=new int[((int)dec4.length())/2];
       for(int i=0;i<(int)dec4.length();i++)
       {
        cou=0;   
        aa="";
           aa=aa+dec4.charAt(i);
           for(int j=0;;j++)
           {
               ssss="";
               ssss=ssss+option[j];
              
               if(aa.charAt(0)==ssss.charAt(0))
               {
                   break;
               }
               cou++;
           }
           aaaa[i]=cou;
           //System.out.println(cou);
          }
          for(int k=0;;k++)
           {
               ssss="";
               ssss=ssss+option[k];
               if(en.charAt((int)en.length()-2)==ssss.charAt(0))
               {
                   break;
               }
               cou2++;
           }
           System.out.println(cou2);
          //System.out.println(option[38]);
           for(int i=0;i<(int)dec4.length();i=i+2)
           {
               mainstr="";
               for(int j=i+1;j<=i+1;j++)
               {
                   ssaa=aaaa[i]*aaaa[j];
               }

               mainstr=mainstr+option[ssaa/cou2];
               main=main+mainstr.charAt(0);
           }
           System.out.println(main);
           System.out.println(ran1);
           System.out.println(ran2);
    
     System.out.format("%s, %s\n",user,pass);
     
     if(ran1.equals("XXXXOTP"))
     {
         main=main+ran2;
         System.out.println(main);
         if(main.equals(jPasswordField1.getText()))
      {
          new homepage().setVisible(true);
      }
      else
      {
          System.out.println("error in username or password");
      }
     }
     if(ran1.equals("OTPXXXX"))
     {
         
         main=ran2+main;
         System.out.println(main);
         if(main.equals(jPasswordField1.getText()))
      {
          new homepage().setVisible(true);
      }
      else
      {
          System.out.println("error in username or password");
      }
     }
     this.dispose();
      
}

    
    
    
    
    if (conn != null) {
        System.out.println("Connected");
    }
    } catch (SQLException ex) {
    ex.printStackTrace();
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
